<script lang="civet">	
    abc := 231
    // 1. first line is being textmate highlighted as a function

    func2 := () ->
	    some1 := 123 // 2. some1 1 char linter

    function getUsers(fetch: typeof globalThis.fetch): Promise<User[]>
            try
                users := '' // 2. user is only 1 char long
                    |> fetch  // 3. fetch not being hoverable
                    |> slice(0, 10) // 4. slice linter goes to the left
                    |> await
                    |> (response: Response) => 
                        if not response.ok
                            throw new Error("HTTP #{response.status}: #{response.statusText}")
                        response
                        // 2. response being only 1 character (just like user)
    
    switch response // 2. response linter being only 1 character 
        {status: 100, body} // 4. status:100 is not hoverable
            console.log body
        {status}
            throw Error `status ${status}`
    
    for fruit1, index of fruits // 5. fruit1, index overlaping each other
        console.log index, fruits

    for fruit1, index in fruits
        console.log index, fruits

    // --- fixed ---
    abc := foo.bar // bar would not be hovered if no semicolon
	    [1..23]

    abc2 := if dbc is not 1 // ref:any linter (generated by civet) were appearing
        {total := 10}

    foo :=
        bar: [
        [1...50].map((range) -> range * range)
        ]    

</script>  
    <!-- when tab before a </script> = linter errors in template are shifted
         TODO: more robust svelte2tsx preprocessor setup  -->
    {total}
    
    