<script lang="civet">
     switch response // 1. response linter being only 1 character / non-existing = non responsive, not hoverable
          {status: 100, body} // 2. status:100 is not hoverable
               console.log body
          {status}
               throw Error `status ${status}`

     func2 := () ->
          some1 := 123 // 3. some1 is either 1 char (can't be hovered on "ome1") or non-existing

     function getUsers(fetch: typeof globalThis.fetch): Promise<User[]>
               try
                    users := '' // 3. user is only 1 char long
                    |> fetch  // 4. fetch not being hoverable or hoverable back
                    |> slice(0, 10) // 4. slice linter goes back
                    |> await
                    |> (response: Response) => 
                         if not response.ok
                              throw new Error("HTTP #{response.status}: #{response.statusText}")
                         response
                         // 3. response being only 1 character (just like user) / non-existing



     for fruit1, index of fruits // 5. fruit1, index overlaping each other
          console.log index, fruits

     for fruit1, index in fruits
          console.log index, fruits

     abc := foo.bar // 6. "bar" would not be hoverable without a semicolon
     [1..23]

     // --- fixed ---
     abc2 := if dbc is not 1 // ref:any linter (generated by civet) were appearing at the := place
          {total := 10}

     foo :=
          bar: [
          [1...50].map((range) -> range * range)
          ]    

     
</script>
    {total}
    
    